services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: backend-despachos
    ports:
      - "8081:8081"
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: despachos_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: backend-ventas
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ventas_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./front_despacho
    container_name: frontend
    ports:
      - "80:80"
    environment:
      BACKEND_VENTAS_URL: http://backend-ventas:8080
      BACKEND_DESPACHOS_URL: http://backend-despachos:8081
    depends_on:
      - backend-despachos
      - backend-ventas

volumes:
  mysql-data:
